#FIX: Remove it from github.
development:
  company:
    name: Vinsol
    domain: vinsol.com

test:
  company:
    name: Vinsol
    domain: vinsol.com

production:
  company:
    name: Vinsol
    domain: vinsol.com
